name: URBAN CONCEPT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44888886506669223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c3a2e'
    - '#fbfbfb'
    - '#030200'
    - '#9a6754'
    - '#a7989f'
  brandStrength: 0.5093823140487075
  lightness: 0.8230025442317128
  saturation: 0.7853346802294254
  rhythmicContrast: 0.45669547468423843
purpose: []
